AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # As per VGG16 model --- It may change depending on the model
BATCH_SIZE: 16
INCLUDE_TOP: False # Only including the conv layers, and not the FC layer
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01