artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/training/model.h5
  training_data: artifacts/data_ingestion/kidney-ct-scan-image
  mlflow_uri: https://dagshub.com/vipul100699/Kidney-Disease-Classification-Deep-Learning-Project.mlflow
  all_params: params.yaml
  params_image_size: [224, 224, 3]
  params_batch_size: 16